config/routes.rb
Rails.application.routes.draw do
	resources :terms do
		resources :related
	end

	root 'welcome#index'

end

app/models/related.rb
class Related < ActiveRecord::Base
	belongs_to :term
	belongs_to :term, class_name: "Term",
                        foreign_key: "related_id"
end

app/models/term.rb
class Term < ActiveRecord::Base
validates :name, uniqueness: { case_sensitive: false }
has_many :relateds
accepts_nested_attributes_for :relateds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/relateds_controller.rb
class RelatedsController < ApplicationController
def create
    @term = Term.find(params[:term_id])
    @related = @term.relateds.create(related_params)
    redirect_to term_path(@term)
  end
 
  private
    def related_params
      params.require(:related).permit(:term_id, :related_id)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
	def index
		@terms = Term.all
	end
			
	def show
		@term = Term.find(params[:id])
	end
	
	def new
		@term = Term.new
		3.times { @term.relateds.build }
	end
	
	def edit
		@term = Term.find(params[:id])
	end

	def create
		@term = Term.new(term_params) 
		@term.save
		redirect_to @term
	end
	
	def update
		@term = Term.find(params[:id])
 
		if @term.update(term_params)
			redirect_to @term
		else
			render 'edit'
		end
	end
	
	def destroy
		@term = Term.find(params[:id])
		@term.destroy
 
		redirect_to term_path
	end
	
private
	def term_params
		params.require(:term).permit(:name, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relateds_helper.rb
module RelatedsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slovar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/terms/_form.html.erb
<%= form_for @term do |f| %>
  <p>
    <%= f.label :name, "Название" %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description, "Описание" %><br>
    <%= f.text_area :description %>
  </p>
  
  <%= f.fields_for :relateds do |builder| %>
		<%= render 'related_fields', :f =>builder %>
	<% end %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/terms/_related_fields.html.erb
<p>
  <%= f.label :related_id, "Id" %><br />
  <%= f.number_field :related_id %><br />
</p>

app/views/terms/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form' %>

<%= link_to 'Обратно к списку статей', term_path %></b>

app/views/terms/index.html.erb
<h1>Словарь</h1>
<%= link_to 'Создать новую статью', new_term_path %>
<table>
  <tr>
    <th>Название</th>
    <th>Опции</th>
    <th colspan="3"></th>
  </tr>
 
  <% @terms.each do |term| %>
    <tr>
		<td><%= link_to term.name, term_path(term) %></td>
		<td><%= link_to 'Редактировать', edit_term_path(term) %></br>
		<%= link_to 'Уничтожить', term_path(term),
						method: :delete,
						data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/terms/new.html.erb
<h1>Новая статья</h1>
<%= render 'form' %>
<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<h1>Статья Name</h1>
<p>
	<strong>Name:</strong>
	<%= @term.name %>
</p>
<p>
	<strong>Description:</strong>
	<%= @term.description %>
</p>

<h2>См. так же:</h2>
<% @term.relateds.each do |related| %>
	<p>
		<%= link_to related.term.name, term_path(term) %>
	</p>
<% end %>


<%= link_to 'Обратно к списку статей', terms_path %></br>
<%= link_to 'Редактировать', edit_term_path(@term) %></br>
<%= link_to 'Удалить', term_path(@term),
						method: :delete,
						data: { confirm: 'Are you sure?' } %></br>

app/views/welcome/index.html.erb
<h1>Словарь</h1>
<%= link_to 'Пристпуть к изучению', controller: 'terms' %>